### ISSUE TITLE
Display Scale other than 100%: The color picker circle widget's position doesn't match the cursor

### ISSUE THREAD

**Issue by niekdomi** [tuberry/color-picker#57] opened 2024-07-14 18:53 UTC
**Describe the bug**
The color picker widget doesn't adapt to other gnome UI scaling than 100%

**To Reproduce**

  - Set Scale to a higher number than 100%
  - Activate the color picker
 -  See error

**Expected behavior**
The color picker circle widget position should match the cursor.

**Comment by tuberry** [comment] 2024-07-15 06:51
Duplicate of #50, please update to GNOME 46 to see if it works.

**Closed as not planned by tuberry** 2024-07-15 06:51 UTC
